require File.expand_path('../app', __FILE__)
require 'sprockets/rails/task'

Rails.application.load_tasks

task :dist do
  puts "cleaning dist ..."
  `rm -rf dist`

  puts "precompiling..."
  `rake assets:precompile`

  puts "launch rails server in production environment"
  pid = spawn("RAILS_ENV=production bundle exec rackup -p 3002 -s thin -P rack.pid")
  Process.detach(pid)
  sleep(3)

  puts "scrap the website..."
  `wget --recursive --page-requisites --html-extension --convert-links --domains localhost -P dist/ localhost:3002`

  puts "killing the server..."
  `kill \`cat rack.pid\``
end