# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-frontend 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-frontend"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Bensoussan"]
  s.date = "2014-05-06"
  s.description = "Build a static frontend app with rails"
  s.email = "mbensoussan.is@gmail.com"
  s.executables = ["rails-frontend"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/rails-frontend",
    "lib/rails-frontend.rb",
    "lib/rails-frontend/cli.rb",
    "lib/rails-frontend/controller.rb",
    "lib/rails-frontend/version.rb",
    "rails-frontend.gemspec",
    "template/.bowerrc",
    "template/.ruby-version",
    "template/Gemfile",
    "template/Guardfile",
    "template/Rakefile",
    "template/app.rb",
    "template/assets/images/troll.jpg",
    "template/assets/javascripts/application.js.coffee",
    "template/assets/stylesheets/application.css.scss",
    "template/boot.rb.erb",
    "template/bower.json.erb",
    "template/config.ru",
    "template/views/index.haml",
    "template/views/layouts/layout.haml",
    "test/helper.rb",
    "test/test_rails-frontend.rb"
  ]
  s.homepage = "http://github.com/mickey/rails-frontend"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Build a static frontend app with rails"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<clamp>, [">= 0"])
      s.add_runtime_dependency(%q<tilt>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["= 4.1.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<clamp>, [">= 0"])
      s.add_dependency(%q<tilt>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["= 4.1.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<clamp>, [">= 0"])
    s.add_dependency(%q<tilt>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["= 4.1.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

